### ISSUE TITLE
Need list of required ports and IPs allowed through firewall for VCS automation and management

### ISSUE THREAD

**Issue by kbroussard** [ibm-cloud-docs/vmwaresolutions#938]
When a customer places their VCS instance behind a firewall, they need explicit documentation as to which ports need to be opened and which IPs need to be able to communicate for VCS automation and management components.  For security conscious customers, who block/deny all by default on their firewall, troubleshooting why VCS automation is hung or why management components are having issues is very complex and time-consuming.

**Comment by delia-rusu** [comment]
Tracked internally in https://github.ibm.com/tornado/tracker/issues/17964

**Comment by delia-rusu** [comment]
Tracked internally in https://github.ibm.com/tornado/tracker/issues/22357

**Comment by delia-rusu** [comment]
This doc is now available internally at https://test.cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-vmwaresol_ports and will be published at the next opportunity.
