### ISSUE TITLE
DPortGroup-Mgmt doesn't exist

### ISSUE THREAD

**Issue by Catoptromancer** [ibm-cloud-docs/vmwaresolutions#939]
The page currently assumes that the VCS automation process, or possibly the reader has created the virtual network SDDC-DPortGroup-Mgmt as is defined in the govc rhcos.json file when you vi and add it in as a network.

Presently if the reader does this, the govc import.ova will fail with "govc: Host did not have any virtual network defined."

**Comment by delia-rusu** [comment]
Tracked internally in https://github.ibm.com/tornado/tracker/issues/19272

**Comment by delia-rusu** [comment]
Issue is fixed and the update will be visible in the next release.
