### ISSUE TITLE
Script has invalid static route to the ESG

### ISSUE THREAD

**Issue by Catoptromancer** [ibm-cloud-docs/vmwaresolutions#940]
Get-NsxEdge OpenShift-ESG | Get-NsxEdgeRouting | New-NsxEdgeStaticRoute -Network 192.168.100.0/24 -NextHop 192.168.133.2 -Vnic 2 -Description "OpenShift Traffic" -confirm:$false

Should in fact be Get-NsxEdge OpenShift-ESG | Get-NsxEdgeRouting | New-NsxEdgeStaticRoute -Network 192.168.133.0/24 -NextHop 192.168.133.2 -Vnic 2 -Description "OpenShift Traffic" -confirm:$false

**Comment by delia-rusu** [comment]
Tracked internally in https://github.ibm.com/tornado/tracker/issues/19272

**Comment by delia-rusu** [comment]
Issue is fixed and the update will be visible in the next release.
