### ISSUE TITLE
ESG Firewall rule tcp/http,tcp/https

### ISSUE THREAD

**Issue by Catoptromancer** [ibm-cloud-docs/vmwaresolutions#941]
Firewall rule in script has invalid syntax
Get-NsxEdge OpenShift-ESG | Get-NsxEdgeFirewall | New-NsxEdgeFirewallRule -Name "Private inbound to OpenShift" -Source 10.0.0.0/8 -Destination 10.72.148.195 -Service tcp/http,tcp/https -Action accept

Should in fact be
Get-NsxEdge OpenShift-ESG | Get-NsxEdgeFirewall | New-NsxEdgeFirewallRule -Name "Private inbound to OpenShift" -Source 10.0.0.0/8 -Destination 10.72.148.195 -Service tcp/80,tcp/443 -Action accept

**Comment by delia-rusu** [comment]
Tracked internally in https://github.ibm.com/tornado/tracker/issues/19272

**Comment by delia-rusu** [comment]
Issue is fixed and the update will be visible in the next release.
