### ISSUE TITLE
ESG firewall rule for bastion

### ISSUE THREAD

**Issue by Catoptromancer** [ibm-cloud-docs/vmwaresolutions#942]
PowerNSX command for defining firewall rule for Bastion host is incorrect and should be
Get-NsxEdge OpenShift-ESG | Get-NsxEdgeFirewall | New-NsxEdgeFirewallRule -Name "SSH inbound to Bastion" -Source 10.0.0.0/8 -Destination 10.72.148.196 -Service tcp/22 -Action accept

**Comment by delia-rusu** [comment]
Tracked internally in https://github.ibm.com/tornado/tracker/issues/19272

**Comment by delia-rusu** [comment]
Issue is fixed and the update will be visible in the next release.
