### ISSUE TITLE
Create DNS Service record for etc superfluous

### ISSUE THREAD

**Issue by Catoptromancer** [ibm-cloud-docs/vmwaresolutions#943]
The command Add-DnsServerResourceRecord -Service "_tcp" –ZoneName

Has either been retired or is superfluous:
Add-DnsServerResourceRecord : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Add-DnsServerResourceRecord -Service "_tcp" –ZoneName

The proceeding Add-DnsServerResourceRecord -Srv etcd-0/1/2 create the service definition.

**Comment by delia-rusu** [comment]
Tracked internally in https://github.ibm.com/tornado/tracker/issues/19272

**Comment by delia-rusu** [comment]
Issue is fixed and the update will be visible in the next release.
