### ISSUE TITLE
Bastion host IP DNS record wrong

### ISSUE THREAD

**Issue by Catoptromancer** [ibm-cloud-docs/vmwaresolutions#944]
According to Bastion initial host setup the ip adds should be 192.168.133.8 . On this page the DNS record is defined as 192.168.133.51

**Comment by delia-rusu** [comment]
Tracked internally in https://github.ibm.com/tornado/tracker/issues/19272

**Comment by delia-rusu** [comment]
Issue is fixed and the update will be visible in the next release.
