### ISSUE TITLE
ESG static route wrong

### ISSUE THREAD

**Issue by Catoptromancer** [ibm-cloud-docs/vmwaresolutions#945]
The fifth ESG static route should be

Get-NsxEdge OpenShift-ESG | Get-NsxEdgeRouting | New-NsxEdgeStaticRoute -Network 192.168.133.0/24 -NextHop 192.168.100.2 -Vnic 2 -Description "OpenShift Traffic" -confirm:$false

Currently -NextHop is 192.168.133.2

**Comment by delia-rusu** [comment]
Tracked internally in https://github.ibm.com/tornado/tracker/issues/19272

**Comment by delia-rusu** [comment]
Changes are published externally, closing.

https://cloud.ibm.com/docs/services/vmwaresolutions?topic=vmware-solutions-openshift-runbook-runbook-intro
