### ISSUE TITLE
DNS Command fails on Window 2012 server

### ISSUE THREAD

**Issue by fctoibm** [ibm-cloud-docs/vmwaresolutions#946]
Add-DnsServerResourceRecord -Service "_tcp"

-Service is not an option

**Comment by delia-rusu** [comment]
Tracked internally in https://github.ibm.com/tornado/tracker/issues/19272

**Comment by delia-rusu** [comment]
Changes are published externally, closing.

https://cloud.ibm.com/docs/services/vmwaresolutions?topic=vmware-solutions-openshift-runbook-runbook-intro
