### ISSUE TITLE
Need to correct all references to Dual Intel Xeon Gold 4210 (Cascade)

### ISSUE THREAD

**Issue by kbroussard** [ibm-cloud-docs/vmwaresolutions#947]
The IBM Cloud Dual Intel Xeon Gold 4210 (Cascade) bare metal server is a Silver not Gold processor.  Some customers make a strong distinction between silver vs gold intel processors, and our portal should be technologically accurate.  Please fix all references to this server especially when ordering for example https://cloud.ibm.com/infrastructure/vmware-solutions/console/ordernew/vcs?bss_account=403aeca5f25bde2ee1fc4324cbfdffdc&ims_account=159827. 

Intel documentation confirming that the 4210 is Silver:
Intel® Xeon® Silver 4210 Processor 
https://ark.intel.com/content/www/us/en/ark/products/193384/intel-xeon-silver-4210-processor-13-75m-cache-2-20-ghz.html

**Comment by delia-rusu** [comment]
Investigating.

**Comment by delia-rusu** [comment]
Updates are being made.

**Comment by delia-rusu** [comment]
Updates completed and verified - will be available with the next release.
