### ISSUE TITLE
Reference table seems to be with incorrect values

### ISSUE THREAD

**Issue by Ravi-S-Github** [ibm-cloud-docs/vmwaresolutions#948]
Hi Team,

The Encryption reference table in page https://cloud.ibm.com/docs/vmwaresolutions?topic=vmware-solutions-htdc-hpcs-encryption-options seems to be with incorrect values as below are incorrect items observed:
Encryption Scope entries for vSphere is written as "Datastore only" and for vSAN is written as "Hypervisor only"
Same with Encryption Granularity: For vSphere column it is mentioned as "per vSAN cluster" and for vSAN it is mentioned as "per VM".

Thanks,
Ravi

**Comment by delia-rusu** [comment]
We're investigating with the SME owner.

**Comment by delia-rusu** [comment]
Fixes were made and the updates will be made available with our next release.
