### ISSUE TITLE
Physical infrastructure design page wrongly mentions 2 IOPS/GB as the NFS spec

### ISSUE THREAD

**Issue by bejoycalias** [ibm-cloud-docs/vmwaresolutions#953]
This page https://cloud.ibm.com/docs/vmwaresolutions?topic=vmware-solutions-design_physicalinfrastructure mentions that the NFS Storage for Management components are with 2 IOPS/GB. Where as this one says 4 IOPS/GB, which should be the correct one - https://cloud.ibm.com/docs/vmwaresolutions?topic=vmware-solutions-design_virtualinfrastructure.

**Comment by delia-rusu** [comment]
Investigating.

**Comment by delia-rusu** [comment]
Updates are in progress: https://test.cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-design_physicalinfrastructure#design_physicalinfrastructure-shared-storage
