### ISSUE TITLE
Prohibited terms: master, slave

### ISSUE THREAD

**Issue by cdmauney** [ibm-cloud-docs/vmwaresolutions#954]
* master: Do not use. Use another term such as "controller", "leader", "manager", "main", "coordinator", "parent", or "primary [server, node, process, or other noun]".
* slave: Do not use. Use another term such as "worker", "child", "helper", "replica", "follower", or "secondary [server, node, process, or other noun]".

List of topics where terms are used:
* https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-htdc-hpcs-deployment
* https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-hcxclient-components

**Comment by delia-rusu** [comment]
Thank you! This is tracked in https://github.ibm.com/tornado/tracker/issues/23892
