### ISSUE TITLE
FSS Cloud needs a detailed Veeam Architecture page

### ISSUE THREAD

**Issue by mark-buckwell** [ibm-cloud-docs/vmwaresolutions#955]
A Veeam architecture page is needed.

The roles within Veeam need to be described as with all the other packages. How can CloudControl be used to create an audit trail of activities performed.

It needs to show how customer-managed certificates and keys are used to secure backups. How can a client use customer-managed certificates for TLS? How can encryption use a customer-managed key from Hyper Protect?

It may be that a new key needs to be created for each server being backed-up. The mechanism on how this is done needs to be included.

**Comment by delia-rusu** [comment]
Response from the owner of the document: `out of scope. Context of Veeam in this architecture is to back up management plane VMs only and not workloads containing customer data.
Veeam on IBM Cloud docs - https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-veeamvm_overview
Veeam detailed docs on encryption - https://helpcenter.veeam.com/docs/backup/vsphere/data_encryption.html?ver=100`
