### ISSUE TITLE
FS Cloud - Enhance page to show how supports NIST zero trust tenets

### ISSUE THREAD

**Issue by mark-buckwell** [ibm-cloud-docs/vmwaresolutions#956]
It would be helpful for this page to show how the solution meetings the draft NIST zero trust basic tenets on page 6 of this document. [https://csrc.nist.gov/publications/detail/sp/800-207/draft](https://csrc.nist.gov/publications/detail/sp/800-207/draft)

Whilst I understand it is not priority, it would help the discussion with clients.

**Comment by delia-rusu** [comment]
Response from the owner of the document: `out side of scope of published design. This is represented in the IBM Cloud Policy Framework available to clients under NDA/MOU. Architectural decisions upon which the design is based are not published publicly.`
