### ISSUE TITLE
Amend/Enhance the use of ISV throughout description for Regulated Workloads

### ISSUE THREAD

**Issue by mark-buckwell** [ibm-cloud-docs/vmwaresolutions#957]
Throughout the documentation there are references to ISV but the context is not explained. This may be the architecture used for the anchor client but other clients are do not have ISVs but might have application developers performing that role. A way of representing this and making application to all clients of the solution is needed.

**Comment by delia-rusu** [comment]
Response from the owner of the document: `Correct as written based upon the primary use case. Future release of the documents may take this feedback into account.`
