### ISSUE TITLE
Veeam Support for IBM COS SSE-KP encryption for Regulated Workloads

### ISSUE THREAD

**Issue by mark-buckwell** [ibm-cloud-docs/vmwaresolutions#959]
Can you document whether IBM COS SSE-KP encryption with Hyper Protect is supported and any specific requirements for setup.
[https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-encryption#encryption-kp](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-encryption#encryption-kp)

**Comment by delia-rusu** [comment]
Response from the owner of the document:
`response - out of scope. No action on this is planned.`
