### ISSUE TITLE
Documentation says a required service is optional in IBM Cloud VMware for Regulated Workloads Architecture

### ISSUE THREAD

**Issue by douglin** [ibm-cloud-docs/vmwaresolutions#960]
There's a comment that says "Security is further enhanced when the optional IBM Hyper Protect Crypto Services (HPCS) service is included with IBM Cloud for VMware Regulated Workloads.".  This text says that HPCS is "optional" but when you actually order, HPCS is a required service.

**Comment by delia-rusu** [comment]
Investigating. This refers to the fifth bullet in https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-fss-overview#fss-overview-management

**Comment by delia-rusu** [comment]
From the doc owner: 

> Change is planed in next doc release to note it is required.
> Doc was correct at time of publication but we changed the design to remove HyTrust DataControl as an encryption option.
