### ISSUE TITLE
Missing networks on legend?

### ISSUE THREAD

**Issue by gwoodroffe** [ibm-cloud-docs/vmwaresolutions#962]
Within Figure 1. IBM Cloud for VMware Regulated Workloads infrastructure overview, there seems to be a number of networks that are not shown on the Legend. Specifically, there are three shades of green and two shades of blue, whereas the Legend only includes one shade of each colour - I can see that some lines might be application flows as opposed to vlans, perhaps? It might also be helpful to show which networks are underlay vs overlay - I would think that the Edge to Management and each Workload cluster would be underlay.

**Comment by delia-rusu** [comment]
Topic that this is opened in reference to: https://test.cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-fss-overview

**Comment by pokeyjo** [comment]
Correct as-is. The one and only overlay network is not only obvious simply by the base design of NSX-T it is the only network called out explicitly in the legend as an overlay network (workload overly network).

The shades of green are not unclear. They are all connected to the exact same perimeter edge firewall and to ESXi hosts. The only reason this diagram does not use a single line to connect all of these together is to imply some level of isolation between the management of each cluster.

No changes planned for this diagram at this time. Please close (jmbrown@us.ibm.com)
