### ISSUE TITLE
Confusing figures

### ISSUE THREAD

**Issue by Risbergg** [ibm-cloud-docs/vmwaresolutions#964]
I think figure 3 and figure 4 must be more explained what services are in the same logical cluster. It is also little confusing use of 'cluster' that can lead to think of the physical Edge service Cluster (ESXi hosts) rather than the logical cluster.

in figure 4 there is a customer T0. Whot does this do in this management cluster?

**Comment by delia-rusu** [comment]
I presume this issue is open in reference to this topic: https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-nsx-t-design

**Comment by pokeyjo** [comment]
description following figure is accurate: 
Tier 0 logical gateway
An NSX-T Tier-0 logical router provides an on and off gateway service between the logical and physical network. For this design, multiple T-0 gateways are deployed for the needs of management, add-on products, and optionally for customer chosen topologies.

It is also little confusing use of 'cluster'  <-- while confusing it is correct and reading VMware documentation and/or taking NSX training classes assists one in understanding this content.

It is assumed that a reader of this documentation is reasonably familiar with the basic VCS architecture.
"what services are in the same logical cluster." <--- the diagrams illustrate a typical VCS.

No changes necessary. Please close. (jmbrown@us.ibm.com)
