### ISSUE TITLE
Although N-VDS is not used, there is a description of N-VDS in docs.

### ISSUE THREAD

**Issue by ytama** [ibm-cloud-docs/vmwaresolutions#970]
Hello,
My understanding is that VCS4.0 (vSphere 7 + NSX-T 3.1) uses VDS instead of N-VDS.
But there is a description of "N-VDS" in some places in the docs below.
https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-nsx-t-design

If the description of the previous version remains, could you correct it?
Thanks,

**Comment by delia-rusu** [comment]
Robley Hall @hallro is working on this.

**Comment by robleyhall** [comment]
PR https://github.ibm.com/cloud-docs/vmwaresolutions/pull/707

**Comment by delia-rusu** [comment]
This is now complete and updates will be available externally with our next release.
