### ISSUE TITLE
Product compatibility guide does not show vSphere 7.x support 

### ISSUE THREAD

**Issue by skuronen** [ibm-cloud-docs/vmwaresolutions#971]
None of the servers here list ESXi 7.x support. 

Intel® Xeon™ Gold 6200/5200 (Cascade Lake-SP) Series | 28 c, 56 t | 6.55.66.55.7 | 0x000506560x00050657 | ESXi 6.7u2, 6.7u1, 6.7, 6.5u3

This list should be updated to reflect the support.

**Comment by delia-rusu** [comment]
Tracked internally in https://github.ibm.com/tornado/tracker/issues/28049
