### ISSUE TITLE
Outdated Veeam Backup information

### ISSUE THREAD

**Issue by carolbh** [ibm-cloud-docs/vmwaresolutions#980]
The following information is outdated. 
"When initially deployed, the IBM Cloud for VMware® Regulated Workloads instances have an all-in-one VM Veeam instance deployment in each region as documented in [Veeam v10a overview](https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-veeamvm_overview). Remove the all-in-one VM Veeam instance deployment in each region and replace it with a single Veeam instance that uses bare metal servers in each region."

Deploying Veeam on Bare Metal is included when ordering/provisioning IC4VRW from the IBM Cloud console.

**Comment by delia-rusu** [comment]
The info was removed and the corrected doc topic will be refreshed with the next release.
