### ISSUE TITLE
https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-vpc-ryo-overview

### ISSUE THREAD

**Issue by lluissabarich** [ibm-cloud-docs/vmwaresolutions#981]
link doesn't work
https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-vpc-ryo-overview

from here: https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-vpc-ryo-overview 
in https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-vpc-ryo-overview#vpc-ryo-overview-links

**Comment by delia-rusu** [comment]
To test and fix all topics that have links to vpc-ryo-overview

**Comment by delia-rusu** [comment]
The info was corrected and it will be refreshed with the next release.
