### ISSUE TITLE
Results after ordering Veeam licenses is incorrect and a note needs to be added on number of licenses

### ISSUE THREAD

**Issue by debbievanzyl** [ibm-cloud-docs/vmwaresolutions#983]
Based on input from the support team, customers have issues with understanding the minimum number of licenses to be purchased and the steps to follow once the purchase has been made.

1. A note needs to be added to the step where the number of licenses are ordered to notify the customer that licenses can only be ordered in multiples of 10.
2. The steps in the results after ordering the Veeam licenses is incorrect. This is not performed automatically and there is a manual step that the customer needs to follow. The results should be the following:

- Once the purchase has been completed, a screenshot of the purchase must be emailed to veeamvpc@us.ibm.com
- A license key will be generated and emailed to the requestor

**Comment by delia-rusu** [comment]
@elleneggers this refers to this topic: https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-veeam_ordering_licenses

**Comment by delia-rusu** [comment]
Updates are completed: https://test.cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-veeam_ordering_licenses
