### ISSUE TITLE
Onpremises IP address limitation is inaccurate

### ISSUE THREAD

**Issue by skuronen** [ibm-cloud-docs/vmwaresolutions#986]
`You cannot use the 172.16.3.x., 172.16.7.x, or 10.0.0.0/8 subnets for your on-premises Virtual Replication Appliance or Zerto Virtual Manager deployments if you are ordering a Zerto Cloud Connector.`

This must present the exact subnets per MZR/Zone, and these need to be fixed to proper CIDR `172.16.3.x.` and `172.16.7.x` >> e.g. `172.16.3.0/24` and `172.16.7.0/24` etc.  

E.g. as per Jim Robbins for DAL12:

![image](https://user-images.githubusercontent.com/27805477/202461163-0c2de2b9-f732-402f-baf9-48a2ea5f7b3a.png)

The limitation should only list the detailed IP address ranges and not the full 10/8.

Also this doc should state that with e.g. with VCS they should not have any overlap issues if they use IBM Cloud provided IP addresses.

**Comment by delia-rusu** [comment]
Internal GH issue opened: https://github.ibm.com/tornado/tracker/issues/40242, will track there.
