### ISSUE TITLE
NSX-T Workload T0 Firewall rule

### ISSUE THREAD

**Issue by neil1taylor** [ibm-cloud-docs/vmwaresolutions#988]
This document should mention that by default, the Workload T0 gateway firewall is set yo deny and that a customer should put in rules to allow traffic to flow

**Comment by delia-rusu** [comment]
@neil1taylor can you please open an issue here https://github.ibm.com/tornado/tracker/issues/new?assignees=drusu&labels=documentation&template=doc-issue-template.md&title=ID%3A+Issue+short+description and include all details so we can get this updated? Thanks!
