### ISSUE TITLE
Remove reference to IBM GTS

### ISSUE THREAD

**Issue by ingoa** [ibm-cloud-docs/vmwaresolutions#989]
The document makes a reference to IBM GTS which no longer exists
> Optional management by IBM
> The VMware Regulated Workloads offering is available as a self-managed or SaaS provider-managed solution. However, a SaaS provider might choose to deploy the IBM Cloud for VMware Regulated Workloads as an IBM-managed offering by bundling in IBM GTS services.

**Comment by delia-rusu** [comment]
Section was removed from the docs and updates will be available with the next product release. Thank you!
