### ISSUE TITLE
updates to byol FAQ after VMW licensing changes

### ISSUE THREAD

**Issue by chrisverrett** [ibm-cloud-docs/vmwaresolutions#990]
Hello,   Can you please update these FAQs to reflect current positioning after the VMW licensing changes

https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-faq_byol

**Comment by delia-rusu** [comment]
Updates are complete - see [How is BYOL affected by the new packaging and pricing on 1 May 2024?](https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-faq_byol#faq_byol-new-pack)
