### ISSUE TITLE
 Distributed Firewall and Advanced Load Balancer listed as included

### ISSUE THREAD

**Issue by skuronen** [ibm-cloud-docs/vmwaresolutions#992]
The following list shows the products that are included:

NSX Advanced Load Balancer
NSX Distributed Firewall

Should not be...needs update.

**Comment by davidyao19** [comment]
We've already made the changes: 
https://test.cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-vpc-vcf-ovw#vpc-vcf-ovw-supported-edition
