### ISSUE TITLE
bring your own license is now supported

### ISSUE THREAD

**Issue by bikasprice** [ibm-cloud-docs/vmwaresolutions#993]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-faq_byol

### What do you think needs to be updated?

This page is no longer correct.  With VCF license portability entitlement clients are able to bring their own VCF license to IBM Cloud.

https://blogs.vmware.com/cloud-foundation/2024/08/22/vmware-cloud-foundation-license-portability-entitlement-comes-to-ibm-cloud/

https://blogs.vmware.com/cloud/2024/01/24/vmware-cloud-foundation-on-ibm-cloud-your-easy-button-for-vcf-deployments/

**Comment by Delia-Rusu1** [comment]
Thank you for your comment. Work is in progress to update this topic and others in the documentation set. We are tracking that doc work internally and will publish the updated docs as we complete them.
